---
run_num: 0
run_name: 'test'
time: 'data_sample.csv//time'
optimization_variable: 'cost'
optimization_sense: 'minimize'

# Environments connection conditions
environments_connections:
  house:
    envs: 'car'
    conditions_type: 'input'
    conditions: 'data_sample.csv//house_car_connection'
    reverse: False
  trailer:
    envs:
      - 'car'
      - 'house'
    conditions_type:
      - 'input'
      - 'input'
    conditions:
      - 'data_sample.csv//trailer_car_connection'
      - 'data_sample.csv//trailer_car_connection'
    reverse:
      - False
      - True