---
run_num: 0
run_name: 'crash_test'
time: 'data_sample.csv//time'
optimization_variable: 'cost'
optimization_sense: 'minimize'

# Environments connection conditions
environments_connections:
  house:
    envs:
      - 'car'
    maximum:
      - 'data_sample.csv//house_car_connection'
    cost_out:
      - 0.
    cost_in:
      - 0.
  module:
    envs:
      - 'car'
      - 'house'
    maximum:
      - 'data_sample.csv//module_car_connection'
      - 'data_sample.csv//module_house_connection'
    cost_out:
      - 0.
      - 0.
    cost_in:
      - 0.
      - 0.